/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_audioconfig_free: (a: number, b: number) => void;
export const __wbg_audioengine_free: (a: number, b: number) => void;
export const __wbg_flute_free: (a: number, b: number) => void;
export const __wbg_get_audioconfig_bird_count: (a: number) => number;
export const __wbg_get_audioconfig_buffer_size: (a: number) => number;
export const __wbg_get_audioconfig_reverb_enabled: (a: number) => number;
export const __wbg_get_audioconfig_sample_rate: (a: number) => number;
export const __wbg_harp_free: (a: number, b: number) => void;
export const __wbg_piano_free: (a: number, b: number) => void;
export const __wbg_set_audioconfig_bird_count: (a: number, b: number) => void;
export const __wbg_set_audioconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_audioconfig_reverb_enabled: (a: number, b: number) => void;
export const __wbg_set_audioconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_strings_free: (a: number, b: number) => void;
export const audioconfig_new: () => number;
export const audioengine_add_bird: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const audioengine_generate_bird_buffer: (a: number, b: number, c: number) => [number, number, number, number];
export const audioengine_generate_breeze: (a: number, b: number, c: number) => [number, number, number, number];
export const audioengine_new: (a: number) => [number, number, number];
export const audioengine_reset: (a: number) => void;
export const audioengine_sample_rate: (a: number) => number;
export const flute_generate: (a: number, b: number, c: number, d: number) => [number, number];
export const flute_new: (a: number) => number;
export const harp_new: (a: number) => number;
export const harp_pluck: (a: number, b: number, c: number) => [number, number];
export const init: () => void;
export const piano_new: (a: number) => number;
export const piano_play_note: (a: number, b: number, c: number) => void;
export const piano_process: (a: number, b: number) => [number, number];
export const strings_generate: (a: number, b: number, c: number) => [number, number];
export const strings_new: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
